## **IMPORT LIBRARIES AND DATA**

In [75]:
import pandas as pd

In [76]:
raw_data = pd.read_csv('https://raw.githubusercontent.com/FTDS-learning-materials/phase-0/main/src/data_ngc.csv')
raw_data

,province_state,country_region,date,latitude,longitude,location_geom,confirmed,deaths,recovered,active,fips,admin2,combined_key
0,NaN,Malaysia,2020-03-08,2.5000,112.5000,POINT(112.5 2.5),99.0,0.0,24.0,NaN,NaN,NaN,NaN
1,NaN,Malaysia,2020-03-10,2.5000,112.5000,POINT(112.5 2.5),129.0,0.0,24.0,NaN,NaN,NaN,NaN
2,NaN,Singapore,2020-03-13,1.3521,103.8198,POINT(103.8198 1.3521),200.0,0.0,97.0,NaN,NaN,NaN,NaN
3,NaN,Malaysia,2020-03-13,4.2105,101.9758,POINT(101.9758 4.2105),197.0,0.0,26.0,NaN,NaN,NaN,NaN
4,NaN,Malaysia,2020-03-15,4.2105,101.9758,POINT(101.9758 4.2105),428.0,0.0,42.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11925,Pahang,Malaysia,2022-06-02,3.8126,103.3256,POINT(103.3256 3.8126),171734.0,975.0,NaN,NaN,NaN,NaN,"Pahang, Malaysia"
11926,Pahang,Malaysia,2022-04-29,3.8126,103.3256,POINT(103.3256 3.8126),170740.0,970.0,NaN,NaN,NaN,NaN,"Pahang, Malaysia"
11927,Pahang,Malaysia,2022-01-10,3.8126,103.3256,POINT(103.3256 3.8126),97320.0,782.0,NaN,NaN,NaN,NaN,"Pahang, Malaysia"
11928,Pahang,Malaysia,2023-02-25,3.8126,103.3256,POINT(103.3256 3.8126),182730.0,1031.0,NaN,NaN,NaN,NaN,"Pahang, Malaysia"
11929,Pahang,Malaysia,2022-09-29,3.8126,103.3256,POINT(103.3256 3.8126),177522.0,1008.0,NaN,NaN,NaN,NaN,"Pahang, Malaysia"

## **DATA CLEANING AND FILTERING**

### Finding Dtypes and Non-Null Count for each column

In [77]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11930 entries, 0 to 11929
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   province_state  9078 non-null   object
 1   country_region  11930 non-null  object
 2   date            11930 non-null  object
 3   latitude        11321 non-null  float64
 4   longitude       11321 non-null  float64
 5   location_geom   11321 non-null  object
 6   confirmed       11929 non-null  float64
 7   deaths          11913 non-null  float64
 8   recovered       1640 non-null   float64
 9   active          1520 non-null   float64
 10  fips            0 non-null      float64
 11  admin2          0 non-null      float64
 12  combined_key    11793 non-null  object
dtypes: float64(8), object(5)
memory usage: 1.2+ MB

### Removing empty columns

In [78]:
raw_data.drop(['fips', 'admin2'], axis=1, inplace=True)

### Removing empty rows

In [79]:
raw_data[raw_data['active'].notna()]

,province_state,country_region,date,latitude,longitude,location_geom,confirmed,deaths,recovered,active,combined_key
413,Unknown,Malaysia,2021-09-22,NaN,NaN,NaN,0.0,0.0,0.0,0.0,"Unknown, Malaysia"
980,Negeri Sembilan,Malaysia,2021-09-22,2.725800,101.942400,POINT(101.9424 2.7258),96054.0,92943.0,1187.0,0.0,"Negeri Sembilan, Malaysia"
1514,Selangor,Malaysia,2021-09-22,3.073800,101.518300,POINT(101.5183 3.0738),664024.0,624641.0,8880.0,0.0,"Selangor, Malaysia"
1707,NaN,Malaysia,2021-05-26,4.210484,101.975766,POINT(101.975766 4.210484),533367.0,2432.0,464727.0,66208.0,Malaysia
1708,NaN,Malaysia,2020-06-07,4.210484,101.975766,POINT(101.975766 4.210484),8322.0,117.0,6674.0,1531.0,Malaysia
...,...,...,...,...,...,...,...,...,...,...,...
9601,W.P. Kuala Lumpur,Malaysia,2021-09-22,3.139000,101.686900,POINT(101.6869 3.139),183867.0,176021.0,2392.0,0.0,"W.P. Kuala Lumpur, Malaysia"
10135,Kedah,Malaysia,2021-09-22,6.118400,100.368500,POINT(100.3685 6.1184),128551.0,117622.0,1710.0,0.0,"Kedah, Malaysia"
10669,Sabah,Malaysia,2021-09-22,5.978800,116.075300,POINT(116.0753 5.9788),189323.0,168086.0,2037.0,0.0,"Sabah, Malaysia"
11203,Johor,Malaysia,2021-09-22,1.485400,103.761800,POINT(103.7618 1.4854),184221.0,152550.0,3012.0,0.0,"Johor, Malaysia"
11737,Pahang,Malaysia,2021-09-22,3.812600,103.325600,POINT(103.3256 3.8126),59094.0,48737.0,557.0,0.0,"Pahang, Malaysia"

In [80]:
raw_data.dropna(subset=['province_state'], inplace=True)

### Drop 'Unknown' values in province_state

In [81]:
no_unknown_data = raw_data[raw_data['province_state'] != 'Unknown']

## **DATA EXPLORATION**

### Group data by province_state and show by sum of confirmed, deaths, and recovered

In [82]:
province_data = no_unknown_data.groupby('combined_key')['confirmed', 'deaths', 'recovered'].sum()
province_data

<ipython-input-82-e3072b437e93>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  province_data = no_unknown_data.groupby('combined_key')['confirmed', 'deaths', 'recovered'].sum()

                               confirmed     deaths  recovered
combined_key
Johor, Malaysia              183340114.0  2461677.0     3012.0
Kedah, Malaysia              140587320.0  1443311.0     1710.0
Kelantan, Malaysia           119538703.0   804498.0      725.0
Melaka, Malaysia              61011677.0   631648.0      824.0
Negeri Sembilan, Malaysia     98025611.0   856382.0     1187.0
Pahang, Malaysia              79664464.0   535045.0      557.0
Perak, Malaysia              101376931.0  1024163.0      775.0
Perlis, Malaysia               7779846.0    92335.0       56.0
Pulau Pinang, Malaysia       133675698.0  1123191.0     1197.0
Sabah, Malaysia              182989419.0  1769180.0     2037.0
Sarawak, Malaysia            155701847.0  1029862.0      710.0
Selangor, Malaysia           655172587.0  6213502.0     8880.0
Terengganu, Malaysia          60051309.0   464353.0      333.0
W.P. Kuala Lumpur, Malaysia  186055777.0  1650447.0     2392.0
W.P. Labuan, Malaysia          9945442.0    91945.0      148.0
W.P. Putrajaya, Malaysia      11009837.0    21586.0       22.0

In [83]:
country_data = raw_data.groupby('country_region')['confirmed', 'deaths', 'recovered'].sum()
country_data

<ipython-input-83-171e97068899>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  country_data = raw_data.groupby('country_region')['confirmed', 'deaths', 'recovered'].sum()

                   confirmed      deaths  recovered
country_region
Malaysia        2.185927e+09  20213125.0    24565.0

## **CONCLUSION**



*   The data only has relevant values for columns province_state and country_region = 'Malaysia'
*   The data has 2 empty columns = 'admin2', 'fibs'